name: Auto Fetch Textage Data

on:
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 配置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          pip install -r requirements.txt

      - name: 运行爬虫脚本
        run: |
          python fetch_data.py

      - name: 提交并推送到仓库
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add titletbl.json
          git commit -m "Auto update textage data" || echo "No changes to commit"
          git push
